# Generated by Django 3.2.8 on 2021-12-04 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('uuid',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('kind', models.CharField(choices=[('BLOG', 'BLOG'), ('NEWS', 'NEWS'), ('ADVERTISING', 'ADVERTISING')], default='BLOG', max_length=100)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('uuid',),
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('like', models.CharField(choices=[('OK', 'OK'), ('GOOD', 'GOOD'), ('DISLIKE', 'DISLIKE')], default='OK', max_length=100)),
            ],
            options={
                'verbose_name': 'PostLike',
                'verbose_name_plural': 'PostLikes',
            },
        ),
    ]
