# Generated by Django 3.2.8 on 2021-12-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_postlike_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlike',
            options={'ordering': ('uuid',), 'verbose_name': 'PostLike', 'verbose_name_plural': 'PostLikes'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='postlike',
            order_with_respect_to=None,
        ),
    ]
