# Generated by Django 3.2.8 on 2021-12-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20211205_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='updated_at'),
        ),
    ]
